const data = [
    {
      img: `${process.env.PUBLIC_URL}/chapeau/1.jpg`,
      title: 'Chapeau Classique',
      rating: 2,
      price: '100',
      description: 'Ce chapeau classique est parfait pour un look élégant en toute saison. Il est conçu avec un tissu de qualité pour assurer confort et style.',
      color: 'rouge',
    },
    {
      img: `${process.env.PUBLIC_URL}/chapeau/2.jpg`,
      title: 'Chapeau de Soleil',
      rating: 4,
      price: '80',
      description: 'Un chapeau de soleil léger, idéal pour les journées en extérieur. Il offre une protection optimale contre les rayons du soleil.',
      color: 'gris',
    },
    {
      img: `${process.env.PUBLIC_URL}/chapeau/3.jpg`,
      title: 'Chapeau Vintage 3',
      rating: 3,
      price: '60',
      description: 'Ce chapeau au style vintage est parfait pour ajouter une touche rétro à votre tenue.',
      color: 'gris',
    },
    {
      img: `${process.env.PUBLIC_URL}/chapeau/4.jpg`,
      title: 'Chapeau en Paille 4',
      rating: 5,
      price: '120',
      description: 'Un chapeau en paille parfait pour l\'été, offrant une excellente ventilation tout en maintenant une allure chic.',
      color: 'orange',
    },
    {
      img: `${process.env.PUBLIC_URL}/chapeau/5.jpg`,
      title: 'Chapeau Fedora 5',
      rating: 4,
      price: '90',
      description: 'Le Fedora, un choix intemporel pour ceux qui cherchent un chapeau à la fois chic et décontracté.',
      color: 'noir',
    },
    {
      img: `${process.env.PUBLIC_URL}/chapeau/6.jpg`,
      title: 'Chapeau en Laine 6',
      rating: 5,
      price: '110',
      description: 'Un chapeau en laine chaud pour les mois d\'hiver, combinant confort et style.',
      color: 'rouge',
    },
    {
      img: `${process.env.PUBLIC_URL}/chapeau/7.jpg`,
      title: 'Chapeau de Pêcheur 7',
      rating: 3,
      price: '70',
      description: 'Ce chapeau pratique pour les sorties en mer ou les randonnées, vous offre protection et confort.',
      color: 'gris',
    },
    {
      img: `${process.env.PUBLIC_URL}/chapeau/8.jpg`,
      title: 'Chapeau Cowboy 8',
      rating: 4,
      price: '95',
      description: 'Un chapeau de style cowboy pour ajouter une touche de caractère à votre look.',
      color: 'gris',
    },
    {
      img: `${process.env.PUBLIC_URL}/chapeau/9.jpg`,
      title: 'Chapeau Fedora Vintage 9',
      rating: 5,
      price: '105',
      description: 'Ce Fedora vintage est une pièce classique qui ne se démode jamais, parfaite pour toute occasion.',
      color: 'jaune',
    },
    {
      img: `${process.env.PUBLIC_URL}/chapeau/10.jpg`,
      title: 'Chapeau de Plage 10',
      rating: 4,
      price: '85',
      description: 'Ce chapeau léger est idéal pour les journées à la plage ou en vacances.',
      color: 'rouge',
    },
    {
      img: `${process.env.PUBLIC_URL}/chapeau/11.jpg`,
      title: 'Chapeau de Feutre 11',
      rating: 5,
      price: '130',
      description: 'Chapeau de feutre de haute qualité pour un look sophistiqué et intemporel.',
      color: 'vert',
    },
    {
      img: `${process.env.PUBLIC_URL}/chapeau/12.jpg`,
      title: 'Chapeau de Ville 12',
      rating: 3,
      price: '75',
      description: 'Chapeau de ville élégant, parfait pour une tenue décontractée en ville.',
      color: 'vert',
    }
  ];
  
  export default data;
  